'Solution'
mate-academy/py-create-file-every-second pull request #14
Opened 2022-02-02 14:51 UTC by 8Men5Camels

2022-02-02 16:52 UTC, denyslipin approved these changes
Nice job!

2022-02-03 12:43 UTC, IvanRamyk requested changes

2022-02-03 12:43 UTC, IvanRamyk commented on app/main.py
> +    now = datetime.datetime.now
```suggestion
    now = datetime.datetime.now()
```

2022-02-03 12:43 UTC, IvanRamyk commented on app/main.py
> +        file_name = 'app-' + now().strftime("%H_%M_%S") + '.log'
```suggestion
        file_name = 'app-' + now.strftime("%H_%M_%S") + '.log'
```

2022-02-03 12:43 UTC, IvanRamyk commented on app/main.py
> +        content = now().strftime("%Y-%m-%d %H:%M:%S.%f")
```suggestion
        content = now.strftime("%Y-%m-%d %H:%M:%S.%f")
```

2022-02-03 12:43 UTC, IvanRamyk commented on app/main.py
> +    now = datetime.datetime.now
If you check the type of `now` you'll see: `<class 'builtin_function_or_method'>`
I believe you forgot to call this method using `()`.

2022-02-03 13:38 UTC, IvanRamyk approved these changes

2022-02-03 13:38 UTC, IvanRamyk commented on app/main.py
> +        content = now.strftime("%Y-%m-%d %H:%M:%S.%f")
The same string you will get via `str(now)`

2026-08-28 06:27 UTC, closed without merging